### ISSUE TITLE
Warning on startup

### ISSUE THREAD

**Issue by ghost** [brunonova/nautilus-admin#19] opened 2016-09-11 12:41 UTC
Since i updated nautilus to 3.21.91.1 version over Debian testing, it shows the next warning, and extension doesn't work:

```
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
/usr/share/nautilus-python/extensions/nautilus-admin.py:19: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Nautilus, GObject, GConf, Gtk, GLib
```

**Comment by brunonova** [comment] 2016-09-11 18:49
I think this warning is harmless. I've seen it before in other programs (like software-properties-gtk in Ubuntu 16.04).

I'll investigate the issue in a virtual machine when I have the time.

**Comment by brunonova** [comment] 2016-10-06 21:04
Sorry for the delay.

I have been trying to put Debian Testing in a VirtualBox, but I haven't succeeded yet.
I have also tried Debian Testing in an LXD container (Nautilus 3.22.0), but `pkexec` didn't work there.

[Someone reported a similar bug in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838967). He said:

> "Open as Administrator" option hasn't worked since upgrade nautilus to
> 3.21.91. "Edit as Administrator" still working normally.

His output of running `nautilus` has this interesting line:

> Unknown option --no-desktop

When I tried running `nautilus --no-desktop` in the container, there wasn't any error.

@bitseater, could you check if "Edit as Administrator" is working or not?
And could you check if the problem in "Open as Administrator" still occurs in the most recent version of Nautilus in Debian Testing?

Either way, I'm going to remove the `--no-desktop` option.
There are also the warning, which I'll try to fix.

**Comment by ghost** [comment] 2016-10-07 19:00
Checked over Debian Testing (Stretch) , with Gnome shell 3.22.0 & Nautilus 3.22.0. Both "Edit as ..." and "Open as ..." working normally now for me, but the warning still appears when running nautilus from terminal. "Run as ..." works normally too.

The warning output :

```
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
/usr/share/nautilus-python/extensions/nautilus-admin.py:19: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import Nautilus, GObject, GConf, Gtk, GLib
```

**Comment by brunonova** [comment] 2016-10-07 19:21
Thank you for testing!

I'll try to fix the warning and remove the `--no-desktop` option.

**Comment by brunonova** [comment] 2016-10-07 20:49
Okay, removing the `--no-desktop` option is a bad idea.
Without it, "Open as Administrator" also **starts a new desktop as the root user** under the user desktop, and even changes the color of the Unity Launcher in Ubuntu.

---

As for the warnings, I couldn't remove the first warning (about Nautilus).
That one is probably caused by [python-nautilus](https://packages.debian.org/sid/python-nautilus) itself, which is what the extension uses, and I can't do anything about it.

The second warning (about GConf) should disappear on the next version when the gconf is removed (pull-request #21).

I'm going to close this issue.
Thanks bitseater for reporting it!

**Closed as completed by brunonova** 2016-10-07 20:49 UTC
Labels: invalid
